### ISSUE TITLE
Opened folder Icon

### ISSUE THREAD

**Issue by thomas-co** [artlaman/chalice-icon-theme#1]

**Comment by artlaman** [comment]
I intentionally haven't added 'expanded folder' icon to Chalice icon pack because I wanted to use original vscode icons for folders, and original 'expanded folder' icon looks like it's gonna puke. I find this animation is extremely distracting.
![VS Code default folder animation](https://media.giphy.com/media/MXivR68gd2qvi0ZtLj/giphy.gif)
An attempt to improve it, hope you enjoy.
![Chalice folder animation](https://media.giphy.com/media/l44jFow1eLPhhNOows/giphy.gif)
Feel free to comment if it sucks. 😀
