### ISSUE TITLE
Is it possible to add icons for Golang and JavaScript?

### ISSUE THREAD

**Issue by akashbdj** [artlaman/chalice-icon-theme#2]
Hey @artlaman, 

Thanks for such a great icon theme. Could you please add support for Golang and JavaScript icon? Really appreciate for your time.

**Comment by artlaman** [comment]
Hello @akashbdj,
Thanks for the feedback 🙂
The reasoning behind this icon theme is that it tries to use as minimum icons as possible. In my opinion, there is no need to use various colored icons, because that's what '.extension' part of a filename is meant for. Icons help, of course, to find files much faster. To distinguish css files from js files etc. But too much icons distract.
And if you have for example golang project there's small chance that you have .go and .js files side by side in the same directory.

Why do you think that **/*** icon is no fit for javascript and golang? Maybe you have .c and .go files side by side?
